#!/usr/bin/env node
import { Command } from 'commander';
import { keygen } from './commands/keygen';
import { register } from './commands/register';
import { verify } from './commands/verify';
import { issue } from './commands/issue';
import { compile } from './commands/compile';

const program = new Command();

program
  .name('agent-trust')
  .description('Open Agent Trust Registry CLI Utilities')
  .version('1.0.0');

program
  .command('keygen')
  .description('Generate a new Ed25519 keypair for your runtime')
  .requiredOption('-i, --issuer-id <string>', 'Your globally unique issuer identifier')
  .option('-o, --out-dir <path>', 'Directory to save the private key', './')
  .action(keygen);

program
  .command('register')
  .description('Generate a compliant issuer_entry JSON file')
  .requiredOption('-i, --issuer-id <string>', 'Your globally unique issuer identifier')
  .requiredOption('-n, --display-name <string>', 'Human-readable name of the runtime')
  .requiredOption('-w, --website <url>', 'Public resolving website of the operator')
  .requiredOption('-c, --contact <email>', 'Security responsible contact email')
  .requiredOption('-k, --public-key <base64url>', 'The base64url Ed25519 public key generated from keygen')
  .option('-o, --out-file <path>', 'Output path for the generated JSON')
  .action(register);

program
  .command('verify')
  .description('Verify an agent attestation JWS against the registry')
  .argument('<attestation>', 'The raw JWT/JWS token string')
  .requiredOption('-a, --audience <url>', 'The origin URL of the service expecting the token')
  .option('-m, --mirror <url>', 'Custom registry mirror URL', 'http://localhost:3000')
  .action(verify);

program
  .command('issue')
  .description('Generate a signed test agent-attestation+jwt token (useful for local integration testing)')
  .requiredOption('-i, --issuer-id <string>', 'Your globally unique issuer identifier')
  .requiredOption('-k, --kid <string>', 'The key ID (kid) of the key used to sign')
  .requiredOption('-p, --private-key <path>', 'Path to your .key file generated by keygen')
  .requiredOption('-a, --audience <url>', 'The origin URL of the service expecting the token')
  .option('-s, --scope <string>', 'Comma-separated list of scopes (e.g., read:email,send:email)', 'read:data')
  .option('-e, --expires-in <seconds>', 'Expiration time in seconds', (val) => parseInt(val, 10), 3600)
  .action(issue);

program
  .command('compile')
  .description('Compiles and signs the final manifest.json from the registry folder')
  .requiredOption('-p, --private-key <key>', 'Ed25519 private key to sign the manifest')
  .action(compile);

program.parse(process.argv);
